### PR TITLE
Expose EditorView up to the parent component after initialization

### PR DESCRIPTION
**Pull request by mattyg**
Thanks for this great component! 

I need to be able to access the EditorView in my parent component. This PR makes the CodeMirror component dispatch a 'ready' event that includes the EditorView, after it has been initialized.

### CODE REVIEW

**Comment by mattyg** [comment]
any chance of getting this merged @SomaticIT

**Comment by rouzwelt** [comment]
yup I came across this issue before, that needing to somehow access the EditorView from this svelte plugin, would be great if this can be merged

**Comment by rouzwelt** [comment]
hey @SomaticIT , have you checked this PR? and what's your thoughts on it? do you think you can merge this? would really appreciate it if we can get a resolution for this soon

**Comment by SomaticIT** [comment]
Hello,
I'm sorry for the delay of my response.
This PR sounds very cool and is perfectly aligned with your needs without compromising common use cases.
Let me merge it and create a release!
Thanks

**Comment by mattyg** [comment]
thank you!

**Pull request merged**
